### ISSUE TITLE
Feature request: Include support for Bitmap strikes

### ISSUE THREAD

**Issue by offalynne** [FontStruct/fonthx#6]
**Is your feature request related to a problem? Please describe.**
Windows' ClearType makes bitmap fonts look like shit in browser when using vector rendering
<img src="https://int10h.org/blog/thumbnails/windows-cleartype-truetype-fonts-embedded-bitmaps.png">

**Describe the solution you'd like**
Support for generating bitmap strikes for pixel fonts for a reasonable number of size factors (1-5?) as well as automatically populating certain glyphs for several specific east asian characters in order to trigger Windows' bitmap fallback mode for pixel fonts: https://int10h.org/blog/2016/01/windows-cleartype-truetype-fonts-embedded-bitmaps/#unleashed-in-the-east

**Describe alternatives you've considered**
Build strikes using (closed source) Fony: http://hukka.ncn.fi/?fony
Using bits'n'picas to vectorize strikes: https://github.com/kreativekorp/bitsnpicas
Manual tuning with FontForge: 😭
Dying alone: ⚰️

**Comment by robmeek** [comment]
Thank you for sharing your issue, and apologies for not responding to this sooner. (For some reason I did not receive a notification.)
I read the blog post you link to.
– Unfortunately I can’t see this as something I will work to implement in this library in the forseeable future.
Good luck with finding a solution!
